package hu.arondev.uni.mobileprog.core.domain

data class Repo(
    var archived: Boolean = false,
    var created_at: String = "",
    var default_branch: String = "",
    var description: String = "",
    var disabled: Boolean = false,
    var fork: Boolean = false,
    var forks: Int = 0,
    var forks_count: Int = 0,
    var full_name: String = "",
    var has_downloads: Boolean = false,
    var has_issues: Boolean = false,
    var has_pages: Boolean = false,
    var has_projects: Boolean = false,
    var has_wiki: Boolean = false,
    var homepage: String = "",
    var html_url: String = "",
    var id: Int = 0,
    var name: String = "",
    var network_count: Int = 0,
    var open_issues_count: Int = 0,
    var owner: Owner = Owner(),
    var `private`: Boolean = false,
    var pushed_at: String = "",
    var size: Int = 0,
    var stargazers_count: Int = 0,
    var subscribers_count: Int = 0,
    var updated_at: String = "",
    var url: String = "",
    var watchers: Int = 0,
    var watchers_count: Int = 0
)